#!/bin/bash
# katch
# 17 Dec 2023
# Disable/enable HDMI display

enable="hyprctl keyword monitor HDMI-A-1,1280x720@60,5120x0,1"
disable="hyprctl keyword monitor HDMI-A-1,disable"

if [ $# = 0 ]; then
  echo -e "Must provide input <enable> or <disable>"
  exit 1
elif [ $1 = "enable" ] ; then
  echo $enable | bash
elif [ $1 = "disable" ] ; then
  echo $disable | bash
else
  echo "Provide input <enable> or <disable>"
fi
